// Copies the customer schemas from byotalk-server (source of truth) into the CLI, pinned to a version.
import { readFileSync, writeFileSync } from "node:fs";

const read = (f) => readFileSync(new URL(`../../byotalk-server/customer-schema/${f}`, import.meta.url), "utf8");
writeFileSync(
  new URL("../src/cli/schema.ts", import.meta.url),
  `// Generated by scripts/sync-schema.mjs from byotalk-server/customer-schema/. Do not edit.
export const SCHEMA_VERSION = 1;
export const POSTGRES_SQL = ${JSON.stringify(read("postgres-v1.sql"))};
export const MYSQL_SQL = ${JSON.stringify(read("mysql-v1.sql"))};
export const MONGODB_SPEC = ${read("mongodb-v1.json").trim()} as const;
`,
);
console.log("src/cli/schema.ts updated");
