// Copies the customer schema from byotalk-server (source of truth) into the CLI, pinned to a version.
import { readFileSync, writeFileSync } from "node:fs";

const src = new URL("../../byotalk-server/customer-schema/v1.sql", import.meta.url);
const sql = readFileSync(src, "utf8");
writeFileSync(
  new URL("../src/cli/schema.ts", import.meta.url),
  `// Generated by scripts/sync-schema.mjs from byotalk-server/customer-schema/v1.sql. Do not edit.\nexport const SCHEMA_VERSION = 1;\nexport const SCHEMA_SQL = ${JSON.stringify(sql)};\n`,
);
console.log("src/cli/schema.ts updated");
